### ISSUE TITLE
General project structure for the Prepare section

### ISSUE THREAD

**Issue by BekaValentine** [mietek/haskell-on-heroku-website#5]
in the Prepare section, i would suggest changing this:

> The tutorial app is a simple web service for storing notes, built with Servant.
> 
> The app includes a Cabal package description file, haskell-on-heroku-tutorial.cabal file, used to declare dependencies, and a Halcyon constraints file, .halcyon/constraints file, used to declare version constraints.

to this:

> Every Haskell on Heroku project must contain at least the source files, and a .cabal file describing the package. The tutorial app, which is a simple web service for storing notes built with Servant, has both of these, plus some extra files, such as a readme, and a Halcyon constraints file .halcyon/constraints, used to declare version constraints.

**Comment by mietek** [comment]
I’m sorry. This project is no longer maintained.
